/*
 * This is sample code generated by rpcgen
 * Modified by yesilzeytin for calculator
 */

#include "calc.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("add(%d, %d) is called\n", argp->a, argp->b);
	result = argp->a + argp->b;

	return &result;
}

int *
sub_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("sub(%d, %d) is called\n", argp->a, argp->b);
	result = argp->a - argp->b;

	return &result;
}

int *
mul_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("mul(%d, %d) is called\n", argp->a, argp->b);
	result = argp->a * argp->b;

	return &result;
}

int *
div_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("div(%d, %d) is called\n", argp->a, argp->b);

	if (argp->b != 0)
		result = argp->a / argp->b;
	else {
		printf("You have tried a zero division. Do not trust the output (it's divided by 1) and please don't try to divide something with 0.\n");
		result = argp->a;
	}

	return &result;
}
